config {
    type: "operations",
    tags: ["functions"]
}

  -- Function to check age eligibility
CREATE OR REPLACE FUNCTION
  `trusted.is_eligible_age`(age INT64)
  RETURNS BOOL AS ( age >= 18 );


  -- Function to check recent car loan (90 days)
CREATE OR REPLACE FUNCTION
  `trusted.has_recent_car_loan`(product_name STRING,
    event_date DATE)
  RETURNS BOOL AS ( product_name = 'Car Loan'
    AND event_date >= DATE_SUB(CURRENT_DATE(), INTERVAL 90 DAY) );
